from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.internship import Internship
from openapi_server.models.internship_with_id import InternshipWithId
from openapi_server import util

from openapi_server.models.internship import Internship  # noqa: E501
from openapi_server.models.internship_with_id import InternshipWithId  # noqa: E501

class AddInternship200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, body=None):  # noqa: E501
        """AddInternship200Response - a model defined in OpenAPI

        :param id: The id of this AddInternship200Response.  # noqa: E501
        :type id: str
        :param body: The body of this AddInternship200Response.  # noqa: E501
        :type body: Internship
        """
        self.openapi_types = {
            'id': str,
            'body': Internship
        }

        self.attribute_map = {
            'id': 'id',
            'body': 'body'
        }

        self._id = id
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'AddInternship200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The addInternship_200_response of this AddInternship200Response.  # noqa: E501
        :rtype: AddInternship200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this AddInternship200Response.


        :return: The id of this AddInternship200Response.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this AddInternship200Response.


        :param id: The id of this AddInternship200Response.
        :type id: str
        """

        self._id = id

    @property
    def body(self) -> Internship:
        """Gets the body of this AddInternship200Response.


        :return: The body of this AddInternship200Response.
        :rtype: Internship
        """
        return self._body

    @body.setter
    def body(self, body: Internship):
        """Sets the body of this AddInternship200Response.


        :param body: The body of this AddInternship200Response.
        :type body: Internship
        """

        self._body = body
