from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.candidate import Candidate
from openapi_server import util

from openapi_server.models.candidate import Candidate  # noqa: E501

class CandidateWithId(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, body=None):  # noqa: E501
        """CandidateWithId - a model defined in OpenAPI

        :param id: The id of this CandidateWithId.  # noqa: E501
        :type id: str
        :param body: The body of this CandidateWithId.  # noqa: E501
        :type body: Candidate
        """
        self.openapi_types = {
            'id': str,
            'body': Candidate
        }

        self.attribute_map = {
            'id': 'id',
            'body': 'body'
        }

        self._id = id
        self._body = body

    @classmethod
    def from_dict(cls, dikt) -> 'CandidateWithId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CandidateWithId of this CandidateWithId.  # noqa: E501
        :rtype: CandidateWithId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this CandidateWithId.


        :return: The id of this CandidateWithId.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CandidateWithId.


        :param id: The id of this CandidateWithId.
        :type id: str
        """

        self._id = id

    @property
    def body(self) -> Candidate:
        """Gets the body of this CandidateWithId.


        :return: The body of this CandidateWithId.
        :rtype: Candidate
        """
        return self._body

    @body.setter
    def body(self, body: Candidate):
        """Sets the body of this CandidateWithId.


        :param body: The body of this CandidateWithId.
        :type body: Candidate
        """

        self._body = body
