from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Candidate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, email=None, phone=None, position=None, education=None, skills=None, experience=None, hours_per_week=None, employment_type=None, links=None, path_to_resume=None):  # noqa: E501
        """Candidate - a model defined in OpenAPI

        :param name: The name of this Candidate.  # noqa: E501
        :type name: str
        :param email: The email of this Candidate.  # noqa: E501
        :type email: str
        :param phone: The phone of this Candidate.  # noqa: E501
        :type phone: str
        :param position: The position of this Candidate.  # noqa: E501
        :type position: str
        :param education: The education of this Candidate.  # noqa: E501
        :type education: str
        :param skills: The skills of this Candidate.  # noqa: E501
        :type skills: str
        :param experience: The experience of this Candidate.  # noqa: E501
        :type experience: str
        :param hours_per_week: The hours_per_week of this Candidate.  # noqa: E501
        :type hours_per_week: int
        :param employment_type: The employment_type of this Candidate.  # noqa: E501
        :type employment_type: str
        :param links: The links of this Candidate.  # noqa: E501
        :type links: str
        :param path_to_resume: The path_to_resume of this Candidate.  # noqa: E501
        :type path_to_resume: str
        """
        self.openapi_types = {
            'name': str,
            'email': str,
            'phone': str,
            'position': str,
            'education': str,
            'skills': str,
            'experience': str,
            'hours_per_week': int,
            'employment_type': str,
            'links': str,
            'path_to_resume': str
        }

        self.attribute_map = {
            'name': 'name',
            'email': 'email',
            'phone': 'phone',
            'position': 'position',
            'education': 'education',
            'skills': 'skills',
            'experience': 'experience',
            'hours_per_week': 'hoursPerWeek',
            'employment_type': 'employmentType',
            'links': 'links',
            'path_to_resume': 'pathToResume'
        }

        self._name = name
        self._email = email
        self._phone = phone
        self._position = position
        self._education = education
        self._skills = skills
        self._experience = experience
        self._hours_per_week = hours_per_week
        self._employment_type = employment_type
        self._links = links
        self._path_to_resume = path_to_resume

    @classmethod
    def from_dict(cls, dikt) -> 'Candidate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Candidate of this Candidate.  # noqa: E501
        :rtype: Candidate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Candidate.


        :return: The name of this Candidate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Candidate.


        :param name: The name of this Candidate.
        :type name: str
        """

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this Candidate.


        :return: The email of this Candidate.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Candidate.


        :param email: The email of this Candidate.
        :type email: str
        """

        self._email = email

    @property
    def phone(self) -> str:
        """Gets the phone of this Candidate.


        :return: The phone of this Candidate.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this Candidate.


        :param phone: The phone of this Candidate.
        :type phone: str
        """

        self._phone = phone

    @property
    def position(self) -> str:
        """Gets the position of this Candidate.


        :return: The position of this Candidate.
        :rtype: str
        """
        return self._position

    @position.setter
    def position(self, position: str):
        """Sets the position of this Candidate.


        :param position: The position of this Candidate.
        :type position: str
        """

        self._position = position

    @property
    def education(self) -> str:
        """Gets the education of this Candidate.


        :return: The education of this Candidate.
        :rtype: str
        """
        return self._education

    @education.setter
    def education(self, education: str):
        """Sets the education of this Candidate.


        :param education: The education of this Candidate.
        :type education: str
        """

        self._education = education

    @property
    def skills(self) -> str:
        """Gets the skills of this Candidate.


        :return: The skills of this Candidate.
        :rtype: str
        """
        return self._skills

    @skills.setter
    def skills(self, skills: str):
        """Sets the skills of this Candidate.


        :param skills: The skills of this Candidate.
        :type skills: str
        """

        self._skills = skills

    @property
    def experience(self) -> str:
        """Gets the experience of this Candidate.


        :return: The experience of this Candidate.
        :rtype: str
        """
        return self._experience

    @experience.setter
    def experience(self, experience: str):
        """Sets the experience of this Candidate.


        :param experience: The experience of this Candidate.
        :type experience: str
        """

        self._experience = experience

    @property
    def hours_per_week(self) -> int:
        """Gets the hours_per_week of this Candidate.


        :return: The hours_per_week of this Candidate.
        :rtype: int
        """
        return self._hours_per_week

    @hours_per_week.setter
    def hours_per_week(self, hours_per_week: int):
        """Sets the hours_per_week of this Candidate.


        :param hours_per_week: The hours_per_week of this Candidate.
        :type hours_per_week: int
        """
        if hours_per_week is not None and hours_per_week > 40:  # noqa: E501
            raise ValueError("Invalid value for `hours_per_week`, must be a value less than or equal to `40`")  # noqa: E501
        if hours_per_week is not None and hours_per_week < 20:  # noqa: E501
            raise ValueError("Invalid value for `hours_per_week`, must be a value greater than or equal to `20`")  # noqa: E501

        self._hours_per_week = hours_per_week

    @property
    def employment_type(self) -> str:
        """Gets the employment_type of this Candidate.


        :return: The employment_type of this Candidate.
        :rtype: str
        """
        return self._employment_type

    @employment_type.setter
    def employment_type(self, employment_type: str):
        """Sets the employment_type of this Candidate.


        :param employment_type: The employment_type of this Candidate.
        :type employment_type: str
        """
        # allowed_values = ["в офисе", "удалённо", "гибрид"]  # noqa: E501
        # if employment_type not in allowed_values:
        #     raise ValueError(
        #         "Invalid value for `employment_type` ({0}), must be one of {1}"
        #         .format(employment_type, allowed_values)
        #     )


        # Так как теперь тип занятости строчного формата без енам валидация проходит в util_queries
        self._employment_type = employment_type

    @property
    def links(self) -> str:
        """Gets the links of this Candidate.


        :return: The links of this Candidate.
        :rtype: str
        """
        return self._links

    @links.setter
    def links(self, links: str):
        """Sets the links of this Candidate.


        :param links: The links of this Candidate.
        :type links: str
        """

        self._links = links

    @property
    def path_to_resume(self) -> str:
        """Gets the path_to_resume of this Candidate.


        :return: The path_to_resume of this Candidate.
        :rtype: str
        """
        return self._path_to_resume

    @path_to_resume.setter
    def path_to_resume(self, path_to_resume: str):
        """Sets the path_to_resume of this Candidate.


        :param path_to_resume: The path_to_resume of this Candidate.
        :type path_to_resume: str
        """

        self._path_to_resume = path_to_resume
