from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.internship_with_id import InternshipWithId
from openapi_server.models.pagination import Pagination
from openapi_server import util

from openapi_server.models.internship_with_id import InternshipWithId  # noqa: E501
from openapi_server.models.pagination import Pagination  # noqa: E501

class GetInternships200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, pagination=None):  # noqa: E501
        """GetInternships200Response - a model defined in OpenAPI

        :param data: The data of this GetInternships200Response.  # noqa: E501
        :type data: List[InternshipWithId]
        :param pagination: The pagination of this GetInternships200Response.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {
            'data': List[InternshipWithId],
            'pagination': Pagination
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination'
        }

        self._data = data
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'GetInternships200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getInternships_200_response of this GetInternships200Response.  # noqa: E501
        :rtype: GetInternships200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[InternshipWithId]:
        """Gets the data of this GetInternships200Response.


        :return: The data of this GetInternships200Response.
        :rtype: List[InternshipWithId]
        """
        return self._data

    @data.setter
    def data(self, data: List[InternshipWithId]):
        """Sets the data of this GetInternships200Response.


        :param data: The data of this GetInternships200Response.
        :type data: List[InternshipWithId]
        """

        self._data = data

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this GetInternships200Response.


        :return: The pagination of this GetInternships200Response.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this GetInternships200Response.


        :param pagination: The pagination of this GetInternships200Response.
        :type pagination: Pagination
        """

        self._pagination = pagination
