from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Internship(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, position=None, education=None, skills=None, department=None, hours_per_week=None, employment_type=None, description=None, status=None):  # noqa: E501
        """Internship - a model defined in OpenAPI

        :param position: The position of this Internship.  # noqa: E501
        :type position: str
        :param education: The education of this Internship.  # noqa: E501
        :type education: str
        :param skills: The skills of this Internship.  # noqa: E501
        :type skills: str
        :param department: The department of this Internship.  # noqa: E501
        :type department: str
        :param hours_per_week: The hours_per_week of this Internship.  # noqa: E501
        :type hours_per_week: int
        :param employment_type: The employment_type of this Internship.  # noqa: E501
        :type employment_type: str
        :param description: The description of this Internship.  # noqa: E501
        :type description: str
        :param status: The status of this Internship.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'position': str,
            'education': str,
            'skills': str,
            'department': str,
            'hours_per_week': int,
            'employment_type': str,
            'description': str,
            'status': str
        }

        self.attribute_map = {
            'position': 'position',
            'education': 'education',
            'skills': 'skills',
            'department': 'department',
            'hours_per_week': 'hoursPerWeek',
            'employment_type': 'employmentType',
            'description': 'description',
            'status': 'status'
        }

        self._position = position
        self._education = education
        self._skills = skills
        self._department = department
        self._hours_per_week = hours_per_week
        self._employment_type = employment_type
        self._description = description
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Internship':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Internship of this Internship.  # noqa: E501
        :rtype: Internship
        """
        return util.deserialize_model(dikt, cls)

    @property
    def position(self) -> str:
        """Gets the position of this Internship.


        :return: The position of this Internship.
        :rtype: str
        """
        return self._position

    @position.setter
    def position(self, position: str):
        """Sets the position of this Internship.


        :param position: The position of this Internship.
        :type position: str
        """

        self._position = position

    @property
    def education(self) -> str:
        """Gets the education of this Internship.


        :return: The education of this Internship.
        :rtype: str
        """
        return self._education

    @education.setter
    def education(self, education: str):
        """Sets the education of this Internship.


        :param education: The education of this Internship.
        :type education: str
        """

        self._education = education

    @property
    def skills(self) -> str:
        """Gets the skills of this Internship.


        :return: The skills of this Internship.
        :rtype: str
        """
        return self._skills

    @skills.setter
    def skills(self, skills: str):
        """Sets the skills of this Internship.


        :param skills: The skills of this Internship.
        :type skills: str
        """

        self._skills = skills

    @property
    def department(self) -> str:
        """Gets the department of this Internship.


        :return: The department of this Internship.
        :rtype: str
        """
        return self._department

    @department.setter
    def department(self, department: str):
        """Sets the department of this Internship.


        :param department: The department of this Internship.
        :type department: str
        """

        self._department = department

    @property
    def hours_per_week(self) -> int:
        """Gets the hours_per_week of this Internship.


        :return: The hours_per_week of this Internship.
        :rtype: int
        """
        return self._hours_per_week

    @hours_per_week.setter
    def hours_per_week(self, hours_per_week: int):
        """Sets the hours_per_week of this Internship.


        :param hours_per_week: The hours_per_week of this Internship.
        :type hours_per_week: int
        """
        if hours_per_week is not None and hours_per_week > 40:  # noqa: E501
            raise ValueError("Invalid value for `hours_per_week`, must be a value less than or equal to `40`")  # noqa: E501
        if hours_per_week is not None and hours_per_week < 20:  # noqa: E501
            raise ValueError("Invalid value for `hours_per_week`, must be a value greater than or equal to `20`")  # noqa: E501

        self._hours_per_week = hours_per_week

    @property
    def employment_type(self) -> str:
        """Gets the employment_type of this Internship.


        :return: The employment_type of this Internship.
        :rtype: str
        """
        return self._employment_type

    @employment_type.setter
    def employment_type(self, employment_type: str):
        """Sets the employment_type of this Internship.


        :param employment_type: The employment_type of this Internship.
        :type employment_type: str
        """
        # allowed_values = ["в офисе", "удалённо", "гибрид"]  # noqa: E501
        # if employment_type not in allowed_values:
        #     raise ValueError(
        #         "Invalid value for `employment_type` ({0}), must be one of {1}"
        #         .format(employment_type, allowed_values)
        #     )

        self._employment_type = employment_type

    @property
    def description(self) -> str:
        """Gets the description of this Internship.


        :return: The description of this Internship.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Internship.


        :param description: The description of this Internship.
        :type description: str
        """

        self._description = description

    @property
    def status(self) -> str:
        """Gets the status of this Internship.


        :return: The status of this Internship.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Internship.


        :param status: The status of this Internship.
        :type status: str
        """
        allowed_values = ["просмотрено", "отложено", "заблокировано"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
