from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Pagination(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, limit=None, offset=None, remaining=None):  # noqa: E501
        """Pagination - a model defined in OpenAPI

        :param total: The total of this Pagination.  # noqa: E501
        :type total: int
        :param limit: The limit of this Pagination.  # noqa: E501
        :type limit: int
        :param offset: The offset of this Pagination.  # noqa: E501
        :type offset: int
        :param remaining: The remaining of this Pagination.  # noqa: E501
        :type remaining: int
        """
        self.openapi_types = {
            'total': int,
            'limit': int,
            'offset': int,
            'remaining': int
        }

        self.attribute_map = {
            'total': 'total',
            'limit': 'limit',
            'offset': 'offset',
            'remaining': 'remaining'
        }

        self._total = total
        self._limit = limit
        self._offset = offset
        self._remaining = remaining

    @classmethod
    def from_dict(cls, dikt) -> 'Pagination':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pagination of this Pagination.  # noqa: E501
        :rtype: Pagination
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this Pagination.

        Общее количество стажировок  # noqa: E501

        :return: The total of this Pagination.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this Pagination.

        Общее количество стажировок  # noqa: E501

        :param total: The total of this Pagination.
        :type total: int
        """

        self._total = total

    @property
    def limit(self) -> int:
        """Gets the limit of this Pagination.

        Количество стажировок на одной странице  # noqa: E501

        :return: The limit of this Pagination.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this Pagination.

        Количество стажировок на одной странице  # noqa: E501

        :param limit: The limit of this Pagination.
        :type limit: int
        """

        self._limit = limit

    @property
    def offset(self) -> int:
        """Gets the offset of this Pagination.

        Количество пропущенных стажировок  # noqa: E501

        :return: The offset of this Pagination.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this Pagination.

        Количество пропущенных стажировок  # noqa: E501

        :param offset: The offset of this Pagination.
        :type offset: int
        """

        self._offset = offset

    @property
    def remaining(self) -> int:
        """Gets the remaining of this Pagination.

        Количество оставшихся стажировок (Общее количество минус количество на текущей странице)  # noqa: E501

        :return: The remaining of this Pagination.
        :rtype: int
        """
        return self._remaining

    @remaining.setter
    def remaining(self, remaining: int):
        """Sets the remaining of this Pagination.

        Количество оставшихся стажировок (Общее количество минус количество на текущей странице)  # noqa: E501

        :param remaining: The remaining of this Pagination.
        :type remaining: int
        """

        self._remaining = remaining
